# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7388f15f20ab5158cb4d12c270e32ccdaa8f168292c9fb5251541a28442c2c0b6b3e7d6e8d6c0bfa746e214239ade3ca081d4a52b077fcbe33dee267eb7a687e

test:
  secret_key_base: b5aa2e96350b641440639eb69847628050bde73960d0c60769d387a6e432c673f8f2c6df550ab18266a0edb770fe45fe901e98af85dbab93d3a69a6a3bcb58ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
